title: GoldMaker
markdown: kramdown
url: ""
baseurl: "/"

# for atom feed
author:
  name: GoldMaker
  email: angganesia@gmail.com

permalink: pretty    
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-google-search-console-verification-file
  
paginate: 4
paginate_path: "/page:num/"

ganalytics: G-TJSQ4D8SZG
google_search_console:
       verification_file_code: 54b942591f95001
google_site_verification: EqDSYzZON_pAUCee2IQPuw6Nm0kSrILUD75lEOdMyS0
enable_google_verification: true


defaults:
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:categories/:title/
  - scope:
      path: "_pages"
    values:
      layout: "page"
      permalink: /:basename:output_ext
      
jekyll-archives:
  enabled:
    - categories
    
include:
  - _pages
  
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
